### ISSUE TITLE
Git verb for pull-request

### ISSUE THREAD

**Issue by hehrhart** [Supermood/dev-handbook#5]
__QUESTION__: What is the list with use cases?

__QUESTION__: Should we also add them in issues or commit names or only in the title of the pull-request?

**Comment by hilnius** [comment]
QUESTION: What is the list with use cases?
Proposition: shouldn't we inspire from an existing guideline ? like 
https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines (referenced on https://www.conventionalcommits.org/en/v1.0.0/)

QUESTION: Should we also add them in issues or commit names or only in the title of the pull-request?
my opinion: only in pull requests, and all pull requests should be merged with a squash strategy ?

**Comment by hehrhart** [comment]
Yes the list in the angular [gitlab](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) is good, I will just add __clean__ for changes of non-business code, like naming and __remove__ for dead code or forgetting to refacto.

>  Should we also add them in issues or commit names or only in the title of the pull-request?

It depends on the choice of the team and if you use the word in a process like this.

> only in pull requests.

Yes good for me too.

> all pull requests should be merged with a squash strategy

Create other issue with this subject. Here we only talk about verb.

**Comment by hilnius** [comment]
@hehrhart I don't really understand the diff between the **clean** and **remove** you suggest and the proposed **style** and **refactor**, defined in the linked styleguide by 

> **style**: Changes that do not affect the meaning of the code (white-space, formatting, etc)
> **refactor**: A code change that neither fixes a bug nor adds a feature

for me, with the following definitions, _naming changes_ fall under the **style** label, and _cleaning/removing dead code_ under the **refactor** label no ?

**Comment by hehrhart** [comment]
Use __style__ when commit impact style (design of pages)
Use __clean__ when commit change norme, name, position files ... with no impact in code or functional.
Use __refactor__ when commit impact code with no impact functional.
